#!/usr/bin/env bash
# creates pidfile, loops, handles signals
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' TERM
trap 'echo "Y U no love me?!";' INT
trap 'rm -f /var/run/myscript.pid; exit' QUIT
while true
do
    echo "To infinity and beyond"
    sleep 1
done
