#!/usr/bin/env bash

# Find the PID of the script
PID=$(pgrep 4-to_infinity_and_beyond)

# If found, stop it using perl's kill function (allowed)
if [ -n "$PID" ]; then
    perl -e "kill 'TERM', $PID"
fi
